version: "3.8"
services:
  postgres:
    privileged: true
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_DATABASE: employee-control
      POSTGRES_USER: employee-control
      POSTGRES_PASSWORD: employee-control
      POSTGRES_USE_RAM: 1
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  atlas:
    image: arigaio/atlas:0.3.7
    ports:
      - "5800:5800"
    volumes:
      - ./schema/.atlas/:/root/.atlas/
      - ./schema/.atlas/storage/:/storage/
    command: serve --storage "sqlite://storage/atlas.db?_fk=1"